---
title: "STAT 2218: Homework 1"
author: "Andrew Levine"
date: "9/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r IMF Data 1}
#Part 1:
#1.
IMF_data <- data.frame(
  country = c("United States","China","Japan","Germany","United Kingdom","France","India",
  "Italy","Brazil","Canada"),
  GDP = c(20513000,13457267,5070626,4029140,2808899,2794696,2689992,
  2086911,1909386,1733706) * 10 ^ 6, 
  Population = c(326766748,1415045928,127185332,82293457,66573504,66233271,1354051854,
  59290969,210867954,36953765),
  Population_Density_Variable = c(0, 1, 1, 1, 1, 1, 1, 1, 0, 0)
)
IMF_data
dim(IMF_data)
```

```{r IMF Data 2}
#2. 
GDP = c(20513000,13457267,5070626,4029140,2808899,2794696,2689992,
2086911,1909386,1733706) * 10 ^ 6
IMF_data$GDP_trillions <- GDP/10^12
IMF_data
```

```{r IMF Data 3}
#3.
str(IMF_data)
#This data set is a data frame. It contains 10 observations, with 5 variables.
```

```{r IMF Data 4}
#4.
GDP_trillions <- GDP/10^12
Average_GDP_Trillions <- mean(GDP_trillions)
Average_GDP_Trillions #This is the central value of the data set, which is calculated 
#from finding the sum of the GDPs and dividing it by the number of countries within the 
#data set.
Median_GDP_Trillions <- median(GDP_trillions)
Median_GDP_Trillions #This is the middle point of the data set. 50% of the GDPs fall above 
#this point, as well as below it.
GDP_Trillions_Standard_Deviation <- sd(GDP_trillions)
GDP_Trillions_Standard_Deviation #This number indicates how spread out the GDPs are, with 
#respect to the average.
```

```{r IMF Data 5}
#5.
Population_Density_Variable = c(0,1,1,1,1,1,1,1,0,0)
High_Population_Density_Countries_Pct <- (mean(Population_Density_Variable)*100)
High_Population_Density_Countries_Pct
#70% of the countires in the data set had a population density greater than 
#100 people/km^2 in 2018.
```

````{r IMF Data 6}
#6.
library(dplyr)
select(IMF_data, GDP, GDP_trillions)
```

```{r IMF Data 7}
#7.
IMF_data[1:5,]
```

```{r IMF Data 8}
#8.
filter(IMF_data, country == "Italy")
```

```{r IMF Data 9}
#9.
filter(IMF_data, GDP_trillions > 3)
```

```{r IMF data 10}
#10.
filter(IMF_data, Population < 125000000 & GDP_trillions >= 2)
```

```{r mtcars 1}
#Part 2:
#1.
str(mtcars)
count(mtcars)
#The data is stored in a data frame. There are 32 cars and 11 variables in this data set.
```

```{r mtcars 2}
#2. The data was extracted from the 1974 Motor Trend U.S. magazine.
```

```{r mtcars 3}
#3.
summary(mtcars$mpg)
#The min, 10.40, represents the lowest fuel economy in the set.
#The Q1, 15.43, represents the 25th percentile fuel economy in the set. 
#It is the median of the min and the median.
#The median, 19.20, represents the middle fuel economy in the set. 
#Half of all the data lies below/above this figure.
#The Q3, 22.80, represents the 75th percentile fuel economy in the set.
#It is the median of the median and the max.
#The max, 33.90, represents the largest fuel economy in the set.
```

```{r mtcars 4}
#4.
filter(mtcars, mpg >= 21)
```

```{r cars2020 1}
#Part 3:
#1.
cars2020 <- read.csv(
  file = "/Users/andrewlevine/Downloads/Statistics II/Cars2020.csv"
)
#View(cars2020)
str(cars2020)
```

```{r cars2020 2, echo = TRUE}
hist(cars2020$CityMPG,
        main = "City Fuel Economies",
        xlab = "City Fuel Economy (MPG)"
)
```

```{r cars2020 3, echo = TRUE}
barplot(table(cars2020$Type),
        main = "Cars by Type",
        xlab = "Car Type",
        ylab = "Number of Cars"
)
```

```{r cars2020 4, echo = TRUE}
plot(x = as.factor(cars2020$Type), y = cars2020$CityMPG,
     xlab = "Car Type",
     ylab = "City Fuel Economy (MPG)"
)
```

```{r HollywoodMovies}
#2.
HollywoodMovies <- read.csv(
  file = "/Users/andrewlevine/Downloads/Statistics II/HollywoodMovies.csv",
)
  #na.strings = "NA"; Missing data in the set is already denoted with "NA" 
#so we do not need to use the function.
#View(HollywoodMovies)
summary(HollywoodMovies$Budget)
Budget_Average = mean(HollywoodMovies$Budget, na.rm = TRUE)
Budget_Average
```

```{r NBA1718}
#3.
NBA1718 <- read.csv( 
  file = "/Users/andrewlevine/Downloads/Statistics II/NBA1718.csv",
)
#View(NBA1718)
Average_PPG = mean(NBA1718$PointsPerGame)
Average_PPG
Median_PPG = median(NBA1718$PointsPerGame)
Median_PPG
```


 